### ISSUE TITLE
关于数据集问题

### ISSUE THREAD

**Issue by cico19891213** [MrYansong/CasSeqGCN#2]
您好 之前看了您的论文 有提到使用了weibo的数据集 这个数据集的引用我去看了原文 同时也去网上找了相关数据集 但是没找到 请问一下您能提供一下weibo的数据集吗 万分感谢 邮箱是1056860284@qq.com 谢谢！

**Comment by MrYansong** [comment]
已分享给你。

**Comment by coder035** [comment]
求分享下weibo的数据集 邮箱是1776310673@qq.com  万分感谢

**Comment by 2000yangyu** [comment]
您好 之前看了您的论文 有提到使用了weibo的数据集 这个数据集的引用我去看了原文 同时也去网上找了相关数据集 但是没找到 请问一下您能提供一下weibo的数据集吗 万分感谢 邮箱是2277263433@qq.com谢谢！

**Comment by cider21** [comment]
作者您好，请问能否提供一下weibo数据集，我去[数据集原文官网](https://www.aminer.cn/influencelocality)找了，但是给的dropbox链接都已经失效，百度云链接1也无法打开。如果方便的话能否发我一下，邮箱1425872718@qq.com，这会对我的论文非常有帮助！感谢！

**Comment by MrYansong** [comment]
https://www.aminer.org/influencelocality  baidu cloud2可以下载

**Comment by cider21** [comment]
我已经下载百度云2中的部分，但是其中只有weibo_network.txt。请问作者是否留存有完整的数据集？这对我的研究帮助很大，感谢您的帮助🥹

**Comment by MrYansong** [comment]
已分享给你邮箱。

**Comment by 2000yangyu** [comment]
谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月13日(星期三) 晚上8:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MrYansong/CasSeqGCN] 关于数据集问题 (Issue #2)





 
已分享给你邮箱。

**Comment by yangyui** [comment]
您好 之前看了您的论文同时也去网上找了相关数据集 但是没找到 请问一下您能提供一下weibo和dblp的数据集吗 万分感谢 邮箱是2277263433@qq.com谢谢！

**Comment by cider21** [comment]
我只有微博数据集。
我用夸克网盘分享了「weibodata.rar」，点击链接即可保存。打开「夸克APP」，无需下载在线播放视频，畅享原画5倍速，支持电视投屏。
链接：https://pan.quark.cn/s/0dbc31fa2243
提取码：xLrz

**Comment by Dengniran** [comment]
> 作者您好，请问能否提供一下weibo数据集，我去[数据集原文官网](https://www.aminer.cn/influencelocality)找了，但是给的dropbox链接都已经失效，百度云链接1也无法打开。如果方便的话能否发我一下，邮箱[1425872718@qq.com](mailto:1425872718@qq.com)，这会对我的论文非常有帮助！感谢！

您好，我最近也找查找weibo
这个数据集，原百度云链接失效了无法找到完整的数据集。方便的话可以请您发一份给我吗？万分感谢！我的邮箱(dengniran@nudt.edu.cn)

**Comment by 1455348750qwe-collab** [comment]
作者您好，请问能否提供一下微博数据集，数据集官网找不到已经如果方便能否发给我一下的话，邮箱[1455348750@qq.com]。十分谢谢！

**Comment by MrYansong** [comment]
> 作者您好，请问能否提供一下微博数据集，数据集官网找不到已经如果方便能否发给我一下的话，邮箱[[1455348750@qq.com](mailto:1455348750@qq.com)]。十分谢谢！

已回复。
