### ISSUE TITLE
关于数据集的处理问题

### ISSUE THREAD

**Issue by jonzhao1123** [MrYansong/CasSeqGCN#3]
博主您好，有了weibo的数据集后应该怎么对他进行处理，放在哪个文件夹才能运行代码呢

**Comment by MrYansong** [comment]
有了微博的数据集，放在根目录下运行就可以

**Comment by jonzhao1123** [comment]
> 有了微博的数据集，放在根目录下运行就可以
博主可以的话能分享一下微博的数据集吗，邮箱zhaojl1123@163.com，万分感谢！祝您生活愉快
